C4001 PiPico Enhanced Presence Detector: C4001_PresenceDetector_Enhanced.ino File Reference
C4001_PresenceDetector_Enhanced.ino File Reference
Enhanced mmWave Presence Detection - Best of Both Worlds.
#include <DFRobot_C4001.h>
Data Structures
struct SensorReading
Contains complete sensor reading with validation flags.
struct DataQuality
Tracks data quality statistics over 30-second intervals.
Macros
#define PIN_STATUS_LED 18
#define PIN_UART_RX 1
#define PIN_UART_TX 0
#define INVERT_LED_LOGIC false
#define LED_BLINK_ON_ERROR true
#define BAUD_DEBUG 115200
#define BAUD_SENSOR 9600
#define SERIAL_TIMEOUT_MS 3000
#define MIN_DETECTION_RANGE_M 0.3
#define MAX_DETECTION_RANGE_M 2.0
#define DETECTION_THRESHOLD 10
#define STABLE_READINGS 2
#define ENABLE_UART_VERIFY true
#define UART_VERIFY_SAMPLES 2
#define DETECTION_LATCH_MS 3000
#define ENABLE_FRETTING eON
#define MAX_VALID_ENERGY 10000000
#define ENABLE_VERBOSE_OUTPUT false
#define ENABLE_STATE_CHANGES true
#define ENABLE_DETAILED_STARTUP true
#define ENABLE_RAW_UART_DEBUG true
#define ENABLE_DATA_QUALITY true
#define VERBOSE_PRINT_EVERY_N 10
#define RAW_UART_PRINT_EVERY_N 5
#define LOOP_DELAY_MS 100
#define ERROR_BLINK_MS 200
#define SENSOR_STARTUP_DELAY_MS 2000
#define MIN_DETECTION_RANGE_CM ((uint16_t)(MIN_DETECTION_RANGE_M * 100))
#define MAX_DETECTION_RANGE_CM ((uint16_t)(MAX_DETECTION_RANGE_M * 100))
Enumerations
enum class DetectionState : uint8_t { NO_TARGET , DETECTED }
Binary state representing presence detection status.
Functions
void initializeSystem (void)
Initializes the complete system including hardware, sensor, and timing.
void initializeHardware (void)
Configures GPIO pins and UART interface.
void initializeSensor (void)
Establishes communication with the C4001 mmWave sensor.
void configureSensor (void)
Configures sensor parameters for presence detection operation.
void flushUARTBuffer (void)
Clears UART receive buffer of startup garbage data.
void showConfigSummary (void)
Displays comprehensive system configuration table.
SensorReading readSensor (void)
Reads current sensor data and validates quality.
bool verifyDetectionUART (void)
Performs additional UART verification reads to confirm detection.
DetectionState evaluateDetection (const SensorReading &reading)
Evaluates sensor reading and applies debouncing logic.
void updateLED (DetectionState state)
Updates LED state based on detection status.
void errorBlinkLED (void)
Blinks LED rapidly to indicate fatal error condition.
void printStateChange (DetectionState state)
Displays formatted notification when detection state changes.
void printVerboseStatus (const SensorReading &reading, DetectionState state)
Displays detailed single-line sensor status for continuous monitoring.
void printRawUART (void)
Captures and displays raw UART data from sensor.
void printDataQualityReport (void)
Displays 30-second data quality statistics summary.
void printBanner (void)
Displays startup banner with version information.
void printSeparator (void)
Prints a horizontal line separator for visual formatting.
void setup ()
Arduino setup function - called once at startup.
void loop ()
Arduino main loop - called repeatedly during operation.
Variables
DFRobot_C4001_UART radarSensor & Serial1
DetectionState currentState = DetectionState::NO_TARGET
DetectionState previousState = DetectionState::NO_TARGET
unsigned long lastDetectionTime = 0
uint8_t consecutiveDetections = 0
uint8_t consecutiveClears = 0
uint32_t loopCounter = 0
uint32_t rawUartCounter = 0
DataQuality dataQuality = {0, 0, 0, 0, 0, 0}
Detailed Description
Enhanced mmWave Presence Detection - Best of Both Worlds.
Combines reliable presence detection with robust debouncing
Uses Speed Mode (Presence mode firmware is broken)
Software latch for stable detection
LED indicator with optional inversion
UART verification for reliability
Comprehensive configuration via #defines
Version
2.6.2 - SALEAE-OPTIMIZED:
Range config optimized to 0.3-2.0m (98%+ coverage vs 81.6%)
Based on analysis of 103 detection samples from logic analyzer
Captures all readings from 0.311m - 1.993m actual range
Fixes 18.4% of valid detections previously rejected below 0.5m
2.6.1 - UPDATES:
Fixed detection range defaults (0.5-3.0m) based on real deployment
Improved UART message capture (100ms timeout, reads complete messages)
Enhanced trailing character handling for complete NMEA frames
2.6 - NEW FEATURES:
Raw UART/NMEA message debugging (see actual sensor output)
Energy value corruption detection & filtering
Startup buffer flushing (clears sensor garbage data)
Data quality statistics (30s reports)
Enhanced verbose output with corruption warnings
Based on real Saleae captures showing:
Binary garbage at startup: \x08\xC23\x9F\xDD\xF5\xFF\xFF
Corrupted energy values (99M+ instead of normal 1k-50k)
NMEA format: $DFDMD,status,targets,range,velocity,energy, , *
Typical detection range in practice: 0.3m - 2.0m
Author
Ethan HWEDK
Date
2025-12-05
Version
2.6.2
Definition in file C4001_PresenceDetector_Enhanced.ino.
Macro Definition Documentation
BAUD_DEBUG
#define BAUD_DEBUG 115200
Definition at line 59 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by initializeSystem().
BAUD_SENSOR
#define BAUD_SENSOR 9600
Definition at line 60 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by initializeHardware(), and initializeSensor().
DETECTION_LATCH_MS
#define DETECTION_LATCH_MS 3000
Definition at line 96 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by evaluateDetection(), printStateChange(), printVerboseStatus(), and showConfigSummary().
DETECTION_THRESHOLD
#define DETECTION_THRESHOLD 10
Definition at line 86 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by configureSensor(), and showConfigSummary().
ENABLE_DATA_QUALITY
#define ENABLE_DATA_QUALITY true
Definition at line 118 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop(), and showConfigSummary().
ENABLE_DETAILED_STARTUP
#define ENABLE_DETAILED_STARTUP true
Definition at line 116 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by initializeSystem().
ENABLE_FRETTING
#define ENABLE_FRETTING eON
Definition at line 101 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by configureSensor(), and showConfigSummary().
ENABLE_RAW_UART_DEBUG
#define ENABLE_RAW_UART_DEBUG true
Definition at line 117 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop(), and showConfigSummary().
ENABLE_STATE_CHANGES
#define ENABLE_STATE_CHANGES true
Definition at line 115 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop().
ENABLE_UART_VERIFY
#define ENABLE_UART_VERIFY true
Definition at line 92 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by evaluateDetection(), and showConfigSummary().
ENABLE_VERBOSE_OUTPUT
#define ENABLE_VERBOSE_OUTPUT false
Definition at line 114 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop().
ERROR_BLINK_MS
#define ERROR_BLINK_MS 200
Definition at line 129 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by errorBlinkLED().
INVERT_LED_LOGIC
#define INVERT_LED_LOGIC false
Definition at line 52 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by initializeHardware(), and updateLED().
LED_BLINK_ON_ERROR
#define LED_BLINK_ON_ERROR true
Definition at line 53 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by initializeSensor().
LOOP_DELAY_MS
#define LOOP_DELAY_MS 100
Definition at line 128 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop(), and showConfigSummary().
MAX_DETECTION_RANGE_CM
#define MAX_DETECTION_RANGE_CM ((uint16_t)(MAX_DETECTION_RANGE_M * 100))
Definition at line 138 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by configureSensor().
MAX_DETECTION_RANGE_M
#define MAX_DETECTION_RANGE_M 2.0
Definition at line 76 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by configureSensor(), readSensor(), showConfigSummary(), and verifyDetectionUART().
MAX_VALID_ENERGY
#define MAX_VALID_ENERGY 10000000
Definition at line 105 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by readSensor().
MIN_DETECTION_RANGE_CM
#define MIN_DETECTION_RANGE_CM ((uint16_t)(MIN_DETECTION_RANGE_M * 100))
Definition at line 137 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by configureSensor().
MIN_DETECTION_RANGE_M
#define MIN_DETECTION_RANGE_M 0.3
Definition at line 75 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by configureSensor(), readSensor(), showConfigSummary(), and verifyDetectionUART().
PIN_STATUS_LED
#define PIN_STATUS_LED 18
Definition at line 47 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by errorBlinkLED(), initializeHardware(), and updateLED().
PIN_UART_RX
#define PIN_UART_RX 1
Definition at line 48 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by initializeSensor().
PIN_UART_TX
#define PIN_UART_TX 0
Definition at line 49 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by initializeSensor().
RAW_UART_PRINT_EVERY_N
#define RAW_UART_PRINT_EVERY_N 5
Definition at line 122 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop().
SENSOR_STARTUP_DELAY_MS
#define SENSOR_STARTUP_DELAY_MS 2000
Definition at line 130 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by configureSensor().
SERIAL_TIMEOUT_MS
#define SERIAL_TIMEOUT_MS 3000
Definition at line 61 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by initializeSystem().
STABLE_READINGS
#define STABLE_READINGS 2
Definition at line 91 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by evaluateDetection(), and showConfigSummary().
UART_VERIFY_SAMPLES
#define UART_VERIFY_SAMPLES 2
Definition at line 93 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by showConfigSummary(), and verifyDetectionUART().
VERBOSE_PRINT_EVERY_N
#define VERBOSE_PRINT_EVERY_N 10
Definition at line 121 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop().
Enumeration Type Documentation
DetectionState
enum class DetectionState : uint8_t strong
Binary state representing presence detection status.
Two possible states:
NO_TARGET: No presence detected or latch expired
DETECTED: Presence confirmed and within latch period
Note
State transitions controlled by evaluateDetection()
Enumerator
NO_TARGET
No valid target detected.
DETECTED
Target presence confirmed.
Definition at line 157 of file C4001_PresenceDetector_Enhanced.ino.
Function Documentation
configureSensor()
void configureSensor (void)
Configures sensor parameters for presence detection operation.
Configuration sequence performed:
Validates range configuration at runtime (MIN < MAX, reasonable values)
Sets sensor to Speed Mode (workaround for broken Presence Mode firmware)
Configures detection range (MIN_DETECTION_RANGE_CM to MAX_DETECTION_RANGE_CM)
Sets detection threshold (DETECTION_THRESHOLD)
Enables/disables micro-motion (fretting) detection
Saves configuration to sensor non-volatile memory
Starts sensor operation
Note
Uses Speed Mode instead of Presence Mode due to firmware bug
Warning
Halts system if MIN_DETECTION_RANGE_M >= MAX_DETECTION_RANGE_M
See also
MIN_DETECTION_RANGE_M, MAX_DETECTION_RANGE_M, DETECTION_THRESHOLD, ENABLE_FRETTING
Definition at line 449 of file C4001_PresenceDetector_Enhanced.ino.
References DETECTION_THRESHOLD, ENABLE_FRETTING, MAX_DETECTION_RANGE_CM, MAX_DETECTION_RANGE_M, MIN_DETECTION_RANGE_CM, MIN_DETECTION_RANGE_M, and SENSOR_STARTUP_DELAY_MS.
Referenced by initializeSystem().
errorBlinkLED()
void errorBlinkLED (void)
Blinks LED rapidly to indicate fatal error condition.
Infinite loop that:
Toggles LED every ERROR_BLINK_MS milliseconds
Never returns (system is halted)
Used when sensor connection fails after max retry attempts
Note
This function never returns - system requires reset after error
Warning
Only called on unrecoverable errors (e.g., sensor not responding)
See also
LED_BLINK_ON_ERROR, ERROR_BLINK_MS, initializeSensor()
Definition at line 817 of file C4001_PresenceDetector_Enhanced.ino.
References ERROR_BLINK_MS, and PIN_STATUS_LED.
Referenced by initializeSensor().
evaluateDetection()
DetectionState evaluateDetection (const SensorReading & reading)
Evaluates sensor reading and applies debouncing logic.
Multi-stage detection algorithm:
Checks if target exists with valid range and non-corrupted energy
Requires STABLE_READINGS consecutive valid readings for confirmation
Optionally performs UART verification for extra robustness
Updates lastDetectionTime on confirmed detection
Applies software latch (stays DETECTED for DETECTION_LATCH_MS)
Returns to NO_TARGET only after latch expires
Parameters
reading Current sensor reading with validation flags
Returns
DetectionState::DETECTED if target confirmed or within latch period
DetectionState::NO_TARGET if no valid detection and latch expired
Note
Software latch prevents flickering during continuous motion
Energy-corrupted readings are rejected to avoid false positives
See also
STABLE_READINGS, DETECTION_LATCH_MS, ENABLE_UART_VERIFY, verifyDetectionUART()
Definition at line 734 of file C4001_PresenceDetector_Enhanced.ino.
References consecutiveClears, consecutiveDetections, dataQuality, DETECTED, DETECTION_LATCH_MS, ENABLE_UART_VERIFY, SensorReading::energyCorrupted, lastDetectionTime, NO_TARGET, STABLE_READINGS, SensorReading::targetCount, SensorReading::valid, and verifyDetectionUART().
Referenced by loop().
flushUARTBuffer()
void flushUARTBuffer (void)
Clears UART receive buffer of startup garbage data.
The C4001 sensor transmits binary garbage on power-up before settling into normal NMEA message format. This function:
Reads and discards all available bytes for up to 500ms
Reports number of bytes cleared for diagnostic purposes
Prevents garbage data from corrupting initial readings
Note
Typical clearing: 40-70 bytes of garbage data (e.g., \x08\xC23\x9F\xDD\xF5\xFF\xFF)
Expected NMEA format after stabilization: $DFDMD,status,targets,range,velocity,energy,,*
Definition at line 521 of file C4001_PresenceDetector_Enhanced.ino.
References Serial1.
Referenced by initializeHardware().
initializeHardware()
void initializeHardware (void)
Configures GPIO pins and UART interface.
Sets up the following hardware:
LED pin as output with initial state based on INVERT_LED_LOGIC
UART interface (Serial1) at configured baud rate
Flushes UART buffer to clear sensor startup garbage
Note
LED state respects INVERT_LED_LOGIC configuration
See also
PIN_STATUS_LED, BAUD_SENSOR, INVERT_LED_LOGIC, flushUARTBuffer()
Definition at line 353 of file C4001_PresenceDetector_Enhanced.ino.
References BAUD_SENSOR, flushUARTBuffer(), INVERT_LED_LOGIC, PIN_STATUS_LED, and Serial1.
Referenced by initializeSystem().
initializeSensor()
void initializeSensor (void)
Establishes communication with the C4001 mmWave sensor.
Attempts to connect to the sensor with retry logic:
Tries up to 5 connection attempts with 1s delay between attempts
Displays connection progress to serial monitor
On failure: shows detailed troubleshooting guide with wiring diagram
On success: proceeds to configureSensor()
Note
Blocks indefinitely on failure with LED error blink if LED_BLINK_ON_ERROR enabled
Warning
System halts if sensor cannot be contacted after max attempts
See also
LED_BLINK_ON_ERROR, errorBlinkLED(), configureSensor()
Definition at line 384 of file C4001_PresenceDetector_Enhanced.ino.
References BAUD_SENSOR, errorBlinkLED(), LED_BLINK_ON_ERROR, PIN_UART_RX, and PIN_UART_TX.
Referenced by initializeSystem().
initializeSystem()
void initializeSystem (void)
Initializes the complete system including hardware, sensor, and timing.
Performs the following initialization sequence:
Starts USB serial communication with SERIAL_TIMEOUT_MS timeout
Prints startup banner
Initializes hardware (LED, UART)
Connects to and configures the mmWave sensor
Displays configuration summary if ENABLE_DETAILED_STARTUP is true
Initializes detection timing baseline
Note
Called once from setup()
See also
initializeHardware(), initializeSensor(), configureSensor()
Definition at line 311 of file C4001_PresenceDetector_Enhanced.ino.
References BAUD_DEBUG, configureSensor(), ENABLE_DETAILED_STARTUP, initializeHardware(), initializeSensor(), lastDetectionTime, printBanner(), printSeparator(), SERIAL_TIMEOUT_MS, and showConfigSummary().
Referenced by setup().
loop()
void loop ()
Arduino main loop - called repeatedly during operation.
Execution sequence each iteration:
Optionally display raw UART data for debugging
Read current sensor state
Evaluate detection with debouncing logic
Update LED to reflect detection state
Print status based on configuration (verbose/state changes)
Display data quality report every 30 seconds
Delay LOOP_DELAY_MS (100ms = 10Hz update rate)
Note
Loop rate is 10Hz with optional UART verification adding ~20-40ms
See also
LOOP_DELAY_MS, readSensor(), evaluateDetection(), updateLED()
Definition at line 254 of file C4001_PresenceDetector_Enhanced.ino.
References currentState, dataQuality, ENABLE_DATA_QUALITY, ENABLE_RAW_UART_DEBUG, ENABLE_STATE_CHANGES, ENABLE_VERBOSE_OUTPUT, evaluateDetection(), LOOP_DELAY_MS, loopCounter, previousState, printDataQualityReport(), printRawUART(), printStateChange(), printVerboseStatus(), RAW_UART_PRINT_EVERY_N, rawUartCounter, readSensor(), updateLED(), and VERBOSE_PRINT_EVERY_N.
printBanner()
void printBanner (void)
Displays startup banner with version information.
Shows:
System title: "mmWave Presence Detection System"
Version number: "Enhanced Edition v2.6.2"
Optimization note: "Saleae-Optimized | 98%+ Coverage"
Note
Called once during system initialization
See also
initializeSystem()
Definition at line 838 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by initializeSystem().
printDataQualityReport()
void printDataQualityReport (void)
Displays 30-second data quality statistics summary.
Reports:
Total readings processed since last report
Valid detections (in-range with good energy) with percentage
Corrupted energy readings with percentage
Out-of-range readings with percentage
All percentages calculated relative to total readings
Note
Automatically called every 30 seconds when ENABLE_DATA_QUALITY is true
Counters reset after each report for rolling statistics
Returns immediately if no data collected (totalReadings == 0)
See also
ENABLE_DATA_QUALITY, DataQuality, dataQuality
Definition at line 1039 of file C4001_PresenceDetector_Enhanced.ino.
References dataQuality.
Referenced by loop().
printRawUART()
void printRawUART (void)
Captures and displays raw UART data from sensor.
Debug functionality that:
Reads available UART data with 100ms timeout
Displays printable characters as-is
Shows non-printable characters in \xHH hex format
Captures trailing \r
characters for complete frames
Identifies and parses NMEA $DFDMD messages
Note
Only called every RAW_UART_PRINT_EVERY_N loops when ENABLE_RAW_UART_DEBUG is true
May show fragmented messages if called mid-transmission
This debug output is separate from main detection logic (for diagnostics only)
Warning
Can interfere with timing if called too frequently
See also
ENABLE_RAW_UART_DEBUG, RAW_UART_PRINT_EVERY_N
Definition at line 972 of file C4001_PresenceDetector_Enhanced.ino.
References Serial1.
Referenced by loop().
printSeparator()
void printSeparator (void)
Prints a horizontal line separator for visual formatting.
Outputs a 42-character dash line for sectioning output
Note
Used to visually separate sections in startup sequence and reports
Definition at line 853 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by initializeSystem().
printStateChange()
void printStateChange (DetectionState state)
Displays formatted notification when detection state changes.
Shows:
Green indicator () and "PRESENCE DETECTED" for DETECTED state
Latch duration information (how long state will persist)
Black indicator () and "NO PRESENCE" for NO_TARGET state
"Monitoring..." status message
Parameters
state New detection state to display
Note
Only displayed when ENABLE_STATE_CHANGES is true
Not called if state hasn't changed since last check
See also
ENABLE_STATE_CHANGES, DETECTION_LATCH_MS, DetectionState
Definition at line 869 of file C4001_PresenceDetector_Enhanced.ino.
References DETECTED, and DETECTION_LATCH_MS.
Referenced by loop().
printVerboseStatus()
void printVerboseStatus (const SensorReading & reading, DetectionState state)
Displays detailed single-line sensor status for continuous monitoring.
Compact format showing:
T: Target count (0 or 1)
R: Range in meters (2 decimal places)
S: Speed in m/s (+ for receding, - for approaching)
E: Energy with corruption flag (! if corrupted)
Cons: Consecutive detection count
/: Valid reading flag
[DETECTED +Xs] or [CLEAR]: State with latch countdown
Parameters
reading Current sensor reading data
state Current detection state
Note
Only called when ENABLE_VERBOSE_OUTPUT is true
Prints every VERBOSE_PRINT_EVERY_N readings to reduce spam
See also
ENABLE_VERBOSE_OUTPUT, VERBOSE_PRINT_EVERY_N
Definition at line 903 of file C4001_PresenceDetector_Enhanced.ino.
References consecutiveDetections, DETECTED, DETECTION_LATCH_MS, SensorReading::energyCorrupted, lastDetectionTime, SensorReading::targetCount, SensorReading::targetEnergy, SensorReading::targetRange, SensorReading::targetSpeed, and SensorReading::valid.
Referenced by loop().
readSensor()
SensorReading readSensor (void)
Reads current sensor data and validates quality.
Performs the following operations:
Reads target count, range, speed, and energy from sensor
Increments total readings counter for quality tracking
Checks for energy corruption (values > MAX_VALID_ENERGY)
Validates range is within MIN_DETECTION_RANGE_M to MAX_DETECTION_RANGE_M
Updates data quality statistics counters
Returns
SensorReading structure containing:
targetCount: Number of detected targets (0 or 1)
targetRange: Distance in meters
targetSpeed: Velocity in m/s (negative=approaching, positive=receding)
targetEnergy: Signal strength (arbitrary units, normal: 1k-50k)
valid: true if range is within configured limits
energyCorrupted: true if energy > MAX_VALID_ENERGY
Note
Energy corruption occurs in ~20% of readings due to sensor firmware issues
See also
SensorReading, MAX_VALID_ENERGY, dataQuality, DataQuality
Definition at line 647 of file C4001_PresenceDetector_Enhanced.ino.
References dataQuality, SensorReading::energyCorrupted, MAX_DETECTION_RANGE_M, MAX_VALID_ENERGY, MIN_DETECTION_RANGE_M, SensorReading::targetCount, SensorReading::targetEnergy, SensorReading::targetRange, SensorReading::targetSpeed, and SensorReading::valid.
Referenced by loop().
setup()
void setup ()
Arduino setup function - called once at startup.
Delegates to initializeSystem() for complete system initialization
See also
initializeSystem()
Definition at line 237 of file C4001_PresenceDetector_Enhanced.ino.
References initializeSystem().
showConfigSummary()
void showConfigSummary (void)
Displays comprehensive system configuration table.
Formatted output showing:
Sensor operational status (RUNNING/ERROR)
Operating mode (Speed Mode acting as Presence-like)
Detection range limits (MIN to MAX in meters)
Threshold settings with readback verification
Fretting (micro-motion) detection status
Software latch duration in seconds
Debouncing parameters (stable readings, UART verification)
Loop rate in Hz
Debug options (raw UART, data quality)
Note
Only displayed if ENABLE_DETAILED_STARTUP is true
Displays warning if sensor workStatus or initStatus indicate error
See also
ENABLE_DETAILED_STARTUP, sSensorStatus_t
Definition at line 556 of file C4001_PresenceDetector_Enhanced.ino.
References DETECTION_LATCH_MS, DETECTION_THRESHOLD, ENABLE_DATA_QUALITY, ENABLE_FRETTING, ENABLE_RAW_UART_DEBUG, ENABLE_UART_VERIFY, LOOP_DELAY_MS, MAX_DETECTION_RANGE_M, MIN_DETECTION_RANGE_M, STABLE_READINGS, and UART_VERIFY_SAMPLES.
Referenced by initializeSystem().
updateLED()
void updateLED (DetectionState state)
Updates LED state based on detection status.
LED behavior:
ON when DetectionState::DETECTED (presence confirmed)
OFF when DetectionState::NO_TARGET (clear)
Respects INVERT_LED_LOGIC for active-low LED configurations
Parameters
state Current detection state (DETECTED or NO_TARGET)
Note
LED logic automatically inverted if INVERT_LED_LOGIC is true
LED remains ON during entire latch period, not just on fresh detections
See also
PIN_STATUS_LED, INVERT_LED_LOGIC, DetectionState
Definition at line 796 of file C4001_PresenceDetector_Enhanced.ino.
References DETECTED, INVERT_LED_LOGIC, and PIN_STATUS_LED.
Referenced by loop().
verifyDetectionUART()
bool verifyDetectionUART (void)
Performs additional UART verification reads to confirm detection.
Reduces false positives by:
Reading sensor UART_VERIFY_SAMPLES times with 10ms intervals
Checking each reading for valid target count and range
Requiring majority agreement for verification (>50% must agree)
Returns
true if majority of verification samples show valid detection
false if verification fails (will reset consecutive detection counter)
Note
Only called when ENABLE_UART_VERIFY is true
Adds ~20-40ms latency to detection but significantly reduces false triggers
See also
ENABLE_UART_VERIFY, UART_VERIFY_SAMPLES, evaluateDetection()
Definition at line 694 of file C4001_PresenceDetector_Enhanced.ino.
References MAX_DETECTION_RANGE_M, MIN_DETECTION_RANGE_M, and UART_VERIFY_SAMPLES.
Referenced by evaluateDetection().
Variable Documentation
consecutiveClears
uint8_t consecutiveClears = 0
Definition at line 199 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by evaluateDetection().
consecutiveDetections
uint8_t consecutiveDetections = 0
Definition at line 198 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by evaluateDetection(), and printVerboseStatus().
currentState
DetectionState currentState = DetectionState::NO_TARGET
Definition at line 195 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop().
dataQuality
DataQuality dataQuality = {0, 0, 0, 0, 0, 0}
Definition at line 204 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by evaluateDetection(), loop(), printDataQualityReport(), and readSensor().
lastDetectionTime
unsigned long lastDetectionTime = 0
Definition at line 197 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by evaluateDetection(), initializeSystem(), and printVerboseStatus().
loopCounter
uint32_t loopCounter = 0
Definition at line 200 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop().
previousState
DetectionState previousState = DetectionState::NO_TARGET
Definition at line 196 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop().
rawUartCounter
uint32_t rawUartCounter = 0
Definition at line 201 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by loop().
Serial1
DFRobot_C4001_UART radarSensor& Serial1
Definition at line 147 of file C4001_PresenceDetector_Enhanced.ino.
Referenced by flushUARTBuffer(), initializeHardware(), and printRawUART().